// <auto-generated />
using System;
using AutoGestionAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoGestionAPI.Migrations
{
    [DbContext(typeof(TuDbContext))]
    [Migration("20261010093818_AjusteNulosCsharp")]
    partial class AjusteNulosCsharp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoGestionAPI.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alumno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumno"));

                    b.Property<string>("Cohorte")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cohorte");

                    b.Property<string>("EstadoAcademico")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("estado_academico");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Legajo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlumno")
                        .HasName("PK__Alumnos__6D77A7F1E4A5E7C7");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.AlumnoMaterium", b =>
                {
                    b.Property<int>("IdAlumnoMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alumno_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlumnoMateria"));

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int")
                        .HasColumnName("id_alumno");

                    b.Property<int>("IdComision")
                        .HasColumnType("int")
                        .HasColumnName("id_comision");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.HasKey("IdAlumnoMateria")
                        .HasName("PK__alumno_m__459153198B055B1C");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdComision");

                    b.HasIndex("IdMateria");

                    b.ToTable("alumno_materia", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Comision", b =>
                {
                    b.Property<int>("IdComision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comision");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComision"));

                    b.Property<string>("Comision1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("comision");

                    b.HasKey("IdComision")
                        .HasName("PK__comision__B25ABED02217EC99");

                    b.ToTable("comision", (string)null);

                    b.HasData(
                        new
                        {
                            IdComision = 1,
                            Comision1 = "A"
                        },
                        new
                        {
                            IdComision = 2,
                            Comision1 = "B"
                        });
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_configuracion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<int?>("FrecuenciaNotificacionDias")
                        .HasColumnType("int")
                        .HasColumnName("frecuencia_notificacion_dias");

                    b.Property<int?>("LimiteParcialesDiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("limite_parciales_diario");

                    b.HasKey("IdConfiguracion");

                    b.ToTable("configuracion_sistema", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Contenido", b =>
                {
                    b.Property<int>("IdContenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contenido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContenido"));

                    b.Property<string>("BibliografiaComplementaria")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("bibliografia_complementaria");

                    b.Property<string>("BibliografiaObligatoria")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("bibliografia_obligatoria");

                    b.Property<string>("Contenido1")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("contenido");

                    b.Property<int>("IdPrograma")
                        .HasColumnType("int")
                        .HasColumnName("id_programa");

                    b.Property<string>("TituloUnidad")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo_unidad");

                    b.Property<int>("Unidad")
                        .HasColumnType("int")
                        .HasColumnName("unidad");

                    b.HasKey("IdContenido")
                        .HasName("PK__contenid__2A39B2EB21356317");

                    b.HasIndex("IdPrograma");

                    b.ToTable("contenidos", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Correlatividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrelativaId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("PlanEstudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelativaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PlanEstudioId");

                    b.ToTable("Correlatividade");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<bool?>("DirectorSuplente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("director_suplente");

                    b.Property<bool>("EsSuplente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("es_suplente");

                    b.Property<DateTime?>("FechaFinSuplencia")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin_suplencia");

                    b.Property<DateTime?>("FechaInicioSuplencia")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio_suplencia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdDocente")
                        .HasName("PK__Docentes__300DB211BD658FA8");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.DocenteMaterium", b =>
                {
                    b.Property<int>("IdDocenteMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_docente_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocenteMateria"));

                    b.Property<int>("IdComision")
                        .HasColumnType("int")
                        .HasColumnName("id_comision");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.HasKey("IdDocenteMateria")
                        .HasName("PK__docente___2FCCA38FB69E9885");

                    b.HasIndex("IdComision");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.ToTable("docente_materia", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.DocenteTipoTitulo", b =>
                {
                    b.Property<int>("IdDocenteTipoTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_docente_tipo_titulo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocenteTipoTitulo"));

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_egreso");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    b.Property<int>("IdTipoTitulo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_titulo");

                    b.Property<string>("Institucion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("institucion");

                    b.HasKey("IdDocenteTipoTitulo")
                        .HasName("PK__docente___7568C5C07414154F");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdTipoTitulo");

                    b.ToTable("docente_tipo_titulo", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Examene", b =>
                {
                    b.Property<int>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExamen"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdComision")
                        .HasColumnType("int")
                        .HasColumnName("id_comision");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<int>("IdTipoExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_examen");

                    b.HasKey("IdExamen")
                        .HasName("PK__Examenes__D16A231D13159B4C");

                    b.HasIndex("IdComision");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdTipoExamen");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Justificativo", b =>
                {
                    b.Property<int>("IdJustificativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_justificativo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJustificativo"));

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_carga");

                    b.Property<DateTime?>("FechaInasistenciaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inasistencia_fin");

                    b.Property<DateTime?>("FechaInasistenciaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inasistencia_inicio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("IdUsuarioAuditor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_auditor");

                    b.Property<string>("NotaAdicional")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("nota_adicional");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<string>("TipoInasistencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_inasistencia");

                    b.HasKey("IdJustificativo")
                        .HasName("PK__Justific__C281B7964782FFF1");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioAuditor");

                    b.ToTable("Justificativos");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Legajo", b =>
                {
                    b.Property<int>("IdLegajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_legajo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLegajo"));

                    b.Property<string>("Comentario")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("comentario");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_carga");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdTipoDoc")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_doc");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("IdUsuarioAuditor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_auditor");

                    b.Property<bool?>("PresentadoFisico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("presentado_fisico");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ruta_archivo");

                    b.HasKey("IdLegajo")
                        .HasName("PK__legajo__AB7BD83CE51012B1");

                    b.HasIndex("IdTipoDoc");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioAuditor");

                    b.ToTable("legajo", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("carrera");

                    b.Property<string>("Curso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("curso");

                    b.Property<string>("Formato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorasCatedra")
                        .HasColumnType("int");

                    b.Property<int?>("HorasTotales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int?>("NroOrden")
                        .HasColumnType("int");

                    b.HasKey("IdMateria")
                        .HasName("PK__materias__7E03FD390CE426B5");

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.MesaExamen", b =>
                {
                    b.Property<int>("IdExamen")
                        .HasColumnType("int")
                        .HasColumnName("id_examen");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    b.Property<string>("EstadoConfirmacion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_confirmacion");

                    b.HasKey("IdExamen", "IdDocente");

                    b.HasIndex("IdDocente");

                    b.ToTable("mesa_examen", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Pai", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPais")
                        .HasName("PK__Pais__0941A3A705EB2089");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.PlanesEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AñoFin")
                        .HasColumnType("int");

                    b.Property<int>("AñoInicio")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanesEstudio");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.PlanesMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("PlanEstudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PlanEstudioId");

                    b.ToTable("PlanesMateria");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ProgramasMaterium", b =>
                {
                    b.Property<int>("IdPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_programa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrograma"));

                    b.Property<string>("CicloLectivo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ciclo_lectivo");

                    b.Property<string>("Condicion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("condicion");

                    b.Property<string>("CondicionLibre")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("condicion_libre");

                    b.Property<string>("CondicionPromocional")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("condicion_promocional");

                    b.Property<string>("CondicionRegular")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("condicion_regular");

                    b.Property<string>("CriteriosEvaluacion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("criterios_evaluacion");

                    b.Property<string>("EstrategiasAcompanamientoVirtualRemoto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("estrategias_acompanamiento_virtual_remoto");

                    b.Property<string>("EstrategiasMetodologicas")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("estrategias_metodologicas");

                    b.Property<string>("Evaluacion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("evaluacion");

                    b.Property<string>("ExamenesVirtuales")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("examenes_virtuales");

                    b.Property<string>("FormatoCurricular")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("formato_curricular");

                    b.Property<string>("Fundamentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorasCuatrimestrales")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("horas_cuatrimestrales");

                    b.Property<string>("HorasSemanales")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("horas_semanales");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<string>("ObjetivosEspecificos")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("objetivos_especificos");

                    b.Property<string>("ObjetivosGenerales")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("objetivos_generales");

                    b.HasKey("IdPrograma")
                        .HasName("PK__programa__DC3C5BC1FCEC3827");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.ToTable("programas_materia", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Provincium", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdProvincia")
                        .HasName("PK__Provinci__66C18BFD56110BC3");

                    b.HasIndex("IdPais");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ReconocimientoSabere", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Comentario")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("comentario");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("int")
                        .HasColumnName("id_alumno");

                    b.Property<int?>("IdDocente")
                        .HasColumnType("int")
                        .HasColumnName("id_docente");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.HasKey("IdSolicitud")
                        .HasName("PK__reconoci__5C0C31F36B3BB113");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdDocente");

                    b.HasIndex("IdMateria");

                    b.ToTable("reconocimiento_saberes", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rol");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__6ABCB5E0ABC90772");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Rol = "Director"
                        },
                        new
                        {
                            IdRol = 2,
                            Rol = "Secretario"
                        },
                        new
                        {
                            IdRol = 3,
                            Rol = "Docente"
                        },
                        new
                        {
                            IdRol = 4,
                            Rol = "Alumno"
                        });
                });

            modelBuilder.Entity("AutoGestionAPI.Models.RolesTiposDocumento", b =>
                {
                    b.Property<int>("IdRolesTiposDocumentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_roles_tipos_documentos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolesTiposDocumentos"));

                    b.Property<bool>("Anual")
                        .HasColumnType("bit")
                        .HasColumnName("anual");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdTipoDoc")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_doc");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("bit")
                        .HasColumnName("obligatorio");

                    b.HasKey("IdRolesTiposDocumentos")
                        .HasName("PK__roles_ti__43644D10900869CA");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDoc");

                    b.ToTable("roles_tipos_documentos", (string)null);

                    b.HasData(
                        new
                        {
                            IdRolesTiposDocumentos = 1,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 1,
                            Obligatorio = false
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 2,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 2,
                            Obligatorio = false
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 3,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 3,
                            Obligatorio = false
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 4,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 4,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 5,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 5,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 6,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 6,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 7,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 7,
                            Obligatorio = false
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 8,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 8,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 9,
                            Anual = false,
                            IdRol = 3,
                            IdTipoDoc = 9,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 10,
                            Anual = false,
                            IdRol = 4,
                            IdTipoDoc = 1,
                            Obligatorio = false
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 11,
                            Anual = false,
                            IdRol = 4,
                            IdTipoDoc = 5,
                            Obligatorio = true
                        },
                        new
                        {
                            IdRolesTiposDocumentos = 12,
                            Anual = false,
                            IdRol = 4,
                            IdTipoDoc = 7,
                            Obligatorio = false
                        });
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TipoExaman", b =>
                {
                    b.Property<int>("IdTipoExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_examen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoExamen"));

                    b.Property<string>("TipoExamen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_examen");

                    b.HasKey("IdTipoExamen")
                        .HasName("PK__tipo_exa__C593611AD6D49A87");

                    b.ToTable("tipo_examen", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoExamen = 1,
                            TipoExamen = "Parcial"
                        },
                        new
                        {
                            IdTipoExamen = 2,
                            TipoExamen = "Recuperatorio"
                        },
                        new
                        {
                            IdTipoExamen = 3,
                            TipoExamen = "Final"
                        });
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TipoTitulo", b =>
                {
                    b.Property<int>("IdTipoTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_titulo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTitulo"));

                    b.Property<string>("NombreTitulo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_titulo");

                    b.HasKey("IdTipoTitulo")
                        .HasName("PK__tipo_tit__59FB2E76850A2BB1");

                    b.ToTable("tipo_titulo", (string)null);
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TiposDocumento", b =>
                {
                    b.Property<int>("IdTipoDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_doc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDoc"));

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_documento");

                    b.HasKey("IdTipoDoc")
                        .HasName("PK__tipos_do__B0A524EA1777309C");

                    b.ToTable("tipos_documentos", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoDoc = 1,
                            NombreDocumento = "DNI"
                        },
                        new
                        {
                            IdTipoDoc = 2,
                            NombreDocumento = "Curriculum Vitae"
                        },
                        new
                        {
                            IdTipoDoc = 3,
                            NombreDocumento = "Titulo Profesional"
                        },
                        new
                        {
                            IdTipoDoc = 4,
                            NombreDocumento = "DDJJ Incompatibilidad Horaria"
                        },
                        new
                        {
                            IdTipoDoc = 5,
                            NombreDocumento = "Apto Medico"
                        },
                        new
                        {
                            IdTipoDoc = 6,
                            NombreDocumento = "Apto Psicologico"
                        },
                        new
                        {
                            IdTipoDoc = 7,
                            NombreDocumento = "Antecedentes Penales"
                        },
                        new
                        {
                            IdTipoDoc = 8,
                            NombreDocumento = "Ley 9680"
                        },
                        new
                        {
                            IdTipoDoc = 9,
                            NombreDocumento = "Certificado De Domicilio"
                        });
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("AfiliacionEmergencia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("afiliacion_emergencia");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("ContactoEmergencia")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contacto_emergencia");

                    b.Property<string>("Cuil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_usuario");

                    b.Property<DateTime?>("ExpiracionToken")
                        .HasColumnType("datetime")
                        .HasColumnName("expiracion_token");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly?>("FechaNac")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nac");

                    b.Property<DateTime?>("FechaUltimaNotificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_ultima_notificacion");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto_perfil");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdProvincia")
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono_emergencia");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_recuperacion");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__4E3E04AD81E34050");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.UsuariosRole", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdUsuarioRol")
                        .HasName("PK__Usuarios__D1F881FE9FF7F1D9");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Usuarios_roles", (string)null);
                });

            modelBuilder.Entity("DocenteExamene", b =>
                {
                    b.Property<int>("IdDocentesIdDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdExamen")
                        .HasColumnType("int");

                    b.HasKey("IdDocentesIdDocente", "IdExamen");

                    b.HasIndex("IdExamen");

                    b.ToTable("DocenteExamene");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Alumno", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Alumnos_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.AlumnoMaterium", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("AlumnoMateria")
                        .HasForeignKey("IdAlumno")
                        .IsRequired()
                        .HasConstraintName("FK_AlumnoMateria_Alumno");

                    b.HasOne("AutoGestionAPI.Models.Comision", "IdComisionNavigation")
                        .WithMany("AlumnoMateria")
                        .HasForeignKey("IdComision")
                        .IsRequired()
                        .HasConstraintName("FK_AlumnoMateria_Comision");

                    b.HasOne("AutoGestionAPI.Models.Materia", "IdMateriaNavigation")
                        .WithMany("AlumnoMateria")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_AlumnoMateria_Materia");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdComisionNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Contenido", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.ProgramasMaterium", "IdProgramaNavigation")
                        .WithMany("Contenidos")
                        .HasForeignKey("IdPrograma")
                        .IsRequired()
                        .HasConstraintName("FK_Contenidos_Programa");

                    b.Navigation("IdProgramaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Correlatividade", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Materia", "Correlativa")
                        .WithMany("CorrelatividadeCorrelativas")
                        .HasForeignKey("CorrelativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoGestionAPI.Models.Materia", "Materia")
                        .WithMany("CorrelatividadeMateria")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoGestionAPI.Models.PlanesEstudio", "PlanEstudio")
                        .WithMany("Correlatividades")
                        .HasForeignKey("PlanEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correlativa");

                    b.Navigation("Materia");

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Docente", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Docentes")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Docentes_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.DocenteMaterium", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Comision", "IdComisionNavigation")
                        .WithMany("DocenteMateria")
                        .HasForeignKey("IdComision")
                        .IsRequired()
                        .HasConstraintName("FK_DocenteMateria_Comision");

                    b.HasOne("AutoGestionAPI.Models.Docente", "IdDocenteNavigation")
                        .WithMany("DocenteMateria")
                        .HasForeignKey("IdDocente")
                        .IsRequired()
                        .HasConstraintName("FK_DocenteMateria_Docente");

                    b.HasOne("AutoGestionAPI.Models.Materia", "IdMateriaNavigation")
                        .WithMany("DocenteMateria")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_DocenteMateria_Materia");

                    b.Navigation("IdComisionNavigation");

                    b.Navigation("IdDocenteNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.DocenteTipoTitulo", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Docente", "IdDocenteNavigation")
                        .WithMany("DocenteTipoTitulos")
                        .HasForeignKey("IdDocente")
                        .IsRequired()
                        .HasConstraintName("FK_DocenteTipoTitulo_Docente");

                    b.HasOne("AutoGestionAPI.Models.TipoTitulo", "IdTipoTituloNavigation")
                        .WithMany("DocenteTipoTitulos")
                        .HasForeignKey("IdTipoTitulo")
                        .IsRequired()
                        .HasConstraintName("FK_DocenteTipoTitulo_TipoTitulo");

                    b.Navigation("IdDocenteNavigation");

                    b.Navigation("IdTipoTituloNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Examene", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Comision", "IdComisionNavigation")
                        .WithMany("Examenes")
                        .HasForeignKey("IdComision")
                        .IsRequired()
                        .HasConstraintName("FK_Examenes_Comision");

                    b.HasOne("AutoGestionAPI.Models.Materia", "IdMateriaNavigation")
                        .WithMany("Examenes")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_Examenes_Materia");

                    b.HasOne("AutoGestionAPI.Models.TipoExaman", "IdTipoExamenNavigation")
                        .WithMany("Examenes")
                        .HasForeignKey("IdTipoExamen")
                        .IsRequired()
                        .HasConstraintName("FK_Examenes_TipoExamen");

                    b.Navigation("IdComisionNavigation");

                    b.Navigation("IdMateriaNavigation");

                    b.Navigation("IdTipoExamenNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Justificativo", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("JustificativoIdUsuarioNavigations")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Justificativos_Usuario");

                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioAuditorNavigation")
                        .WithMany("JustificativoIdUsuarioAuditorNavigations")
                        .HasForeignKey("IdUsuarioAuditor")
                        .HasConstraintName("FK_Justificativos_Auditor");

                    b.Navigation("IdUsuarioAuditorNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Legajo", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.TiposDocumento", "IdTipoDocNavigation")
                        .WithMany("Legajos")
                        .HasForeignKey("IdTipoDoc")
                        .IsRequired()
                        .HasConstraintName("FK_Legajo_TipoDoc");

                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("LegajoIdUsuarioNavigations")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Legajo_Usuario");

                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioAuditorNavigation")
                        .WithMany("LegajoIdUsuarioAuditorNavigations")
                        .HasForeignKey("IdUsuarioAuditor")
                        .HasConstraintName("FK_Legajo_Auditor");

                    b.Navigation("IdTipoDocNavigation");

                    b.Navigation("IdUsuarioAuditorNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.MesaExamen", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Docente", "IdDocenteNavigation")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .IsRequired()
                        .HasConstraintName("FK_MesaExamen_Docente");

                    b.HasOne("AutoGestionAPI.Models.Examene", "IdExamenNavigation")
                        .WithMany()
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MesaExamen_Examen");

                    b.Navigation("IdDocenteNavigation");

                    b.Navigation("IdExamenNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.PlanesMateria", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Materia", "Materia")
                        .WithMany("PlanesMateria")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoGestionAPI.Models.PlanesEstudio", "PlanEstudio")
                        .WithMany("PlanesMateria")
                        .HasForeignKey("PlanEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ProgramasMaterium", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Docente", "IdDocenteNavigation")
                        .WithMany("ProgramasMateria")
                        .HasForeignKey("IdDocente")
                        .IsRequired()
                        .HasConstraintName("FK_ProgramasMateria_Docente");

                    b.HasOne("AutoGestionAPI.Models.Materia", "IdMateriaNavigation")
                        .WithMany("ProgramasMateria")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_ProgramasMateria_Materia");

                    b.Navigation("IdDocenteNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Provincium", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Pai", "IdPaisNavigation")
                        .WithMany("Provincia")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Provincia_Pais");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ReconocimientoSabere", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Alumno", "IdAlumnoNavigation")
                        .WithMany("ReconocimientoSaberes")
                        .HasForeignKey("IdAlumno")
                        .IsRequired()
                        .HasConstraintName("FK_Reconocimiento_Alumno");

                    b.HasOne("AutoGestionAPI.Models.Docente", "IdDocenteNavigation")
                        .WithMany("ReconocimientoSaberes")
                        .HasForeignKey("IdDocente")
                        .HasConstraintName("FK_Reconocimiento_Docente");

                    b.HasOne("AutoGestionAPI.Models.Materia", "IdMateriaNavigation")
                        .WithMany("ReconocimientoSaberes")
                        .HasForeignKey("IdMateria")
                        .IsRequired()
                        .HasConstraintName("FK_Reconocimiento_Materia");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdDocenteNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.RolesTiposDocumento", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Role", "IdRolNavigation")
                        .WithMany("RolesTiposDocumentos")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_RolesTiposDoc_Rol");

                    b.HasOne("AutoGestionAPI.Models.TiposDocumento", "IdTipoDocNavigation")
                        .WithMany("RolesTiposDocumentos")
                        .HasForeignKey("IdTipoDoc")
                        .IsRequired()
                        .HasConstraintName("FK_RolesTiposDoc_TipoDoc");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdTipoDocNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Usuario", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Provincium", "IdProvinciaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdProvincia")
                        .HasConstraintName("FK_Usuarios_Provincia");

                    b.Navigation("IdProvinciaNavigation");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.UsuariosRole", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Role", "IdRolNavigation")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_Rol");

                    b.HasOne("AutoGestionAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuariosRoles_Usuario");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DocenteExamene", b =>
                {
                    b.HasOne("AutoGestionAPI.Models.Docente", null)
                        .WithMany()
                        .HasForeignKey("IdDocentesIdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoGestionAPI.Models.Examene", null)
                        .WithMany()
                        .HasForeignKey("IdExamen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoMateria");

                    b.Navigation("ReconocimientoSaberes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Comision", b =>
                {
                    b.Navigation("AlumnoMateria");

                    b.Navigation("DocenteMateria");

                    b.Navigation("Examenes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Docente", b =>
                {
                    b.Navigation("DocenteMateria");

                    b.Navigation("DocenteTipoTitulos");

                    b.Navigation("ProgramasMateria");

                    b.Navigation("ReconocimientoSaberes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Materia", b =>
                {
                    b.Navigation("AlumnoMateria");

                    b.Navigation("CorrelatividadeCorrelativas");

                    b.Navigation("CorrelatividadeMateria");

                    b.Navigation("DocenteMateria");

                    b.Navigation("Examenes");

                    b.Navigation("PlanesMateria");

                    b.Navigation("ProgramasMateria");

                    b.Navigation("ReconocimientoSaberes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Pai", b =>
                {
                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.PlanesEstudio", b =>
                {
                    b.Navigation("Correlatividades");

                    b.Navigation("PlanesMateria");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.ProgramasMaterium", b =>
                {
                    b.Navigation("Contenidos");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Provincium", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Role", b =>
                {
                    b.Navigation("RolesTiposDocumentos");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TipoExaman", b =>
                {
                    b.Navigation("Examenes");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TipoTitulo", b =>
                {
                    b.Navigation("DocenteTipoTitulos");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.TiposDocumento", b =>
                {
                    b.Navigation("Legajos");

                    b.Navigation("RolesTiposDocumentos");
                });

            modelBuilder.Entity("AutoGestionAPI.Models.Usuario", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Docentes");

                    b.Navigation("JustificativoIdUsuarioAuditorNavigations");

                    b.Navigation("JustificativoIdUsuarioNavigations");

                    b.Navigation("LegajoIdUsuarioAuditorNavigations");

                    b.Navigation("LegajoIdUsuarioNavigations");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
